# Metadata file for Winters, a utility tool for Endless Sky
# --< https://github.com/a-random-lemurian/winters >-------
name: Lemuria's Extra ES Stuff
version: v0.10.3
mainAuthor: Lemuria
spdxLicenseId: GPL-3.0-or-later
sourceControl:
  system: git
  mainRemote: https://github.com/a-random-lemurian/Lemurias-Extra-ES-Stuff.git